project_id = "vzalrnwnpzbpzvcrjitt"

[functions.send-report-notification]
verify_jwt = false

[functions.log-login-event]
verify_jwt = false

[functions.create-user-admin]
verify_jwt = true

[functions.export-database]
verify_jwt = true

[functions.import-database]
verify_jwt = true

[functions.create-admin]
verify_jwt = false

[functions.send-email]
verify_jwt = true

[functions.send-budget-notification]
verify_jwt = false

[functions.process-inbound-email]
verify_jwt = false

[functions.send-error-response-notification]
verify_jwt = true

[functions.setup-demo-data]
verify_jwt = false

[functions.send-verification-code]
verify_jwt = false

[functions.verify-verification-code]
verify_jwt = false

[functions.send-password-reset]
verify_jwt = false

[functions.verify-password-reset]
verify_jwt = false

[functions.fetch-nbp-rates]
verify_jwt = false
