project_id = "vzalrnwnpzbpzvcrjitt"

[functions.send-report-notification]
verify_jwt = false

[functions.log-login-event]
verify_jwt = false

[functions.create-user-admin]
verify_jwt = true

[functions.export-database]
verify_jwt = true

[functions.import-database]
verify_jwt = true

[functions.create-admin]
verify_jwt = false

[functions.send-email]
verify_jwt = true

[functions.process-inbound-email]
verify_jwt = false
